CF_DEV_ORG: DPSE-ASIA
CF_UAT_ORG: DPSE-ASIA
CF_PROD_ORG: DPSE-ASIA

MY_ENV_VAR: test-my-env-var

GIT_SSH_URI: ssh://git@git.platform.manulife.io:2222/alan_tsui/mongo-atlas-migrate-demo.git
GIT_PRIVATE_KEY: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIJKQIBAAKCAgEA5RRQKvtuP/VDIGi3dyDKtAgwMFP1lCT63AqLxG34l9hhe4dt
    49yLRU+aEvP/69ncwUnlD7PeKT27DeRk7NU931WVuSluFszhC7xHbqbrm0xF3dUr
    3UKwNXQh7aDdFDQQaytbD2NZqRqJYm39Kdv4R1fwP1srHj3wq/GzzIPk3LhH8AxP
    oboQ06vl3fnO6EhGPdH2vCru7HO3zdYSuwomk4X6GbVgCUBFNE6Qlkvafuexu0C1
    Js+65ZjChzpdXY9Aut5lUh8oW1hzvvh4h/+VtuyNRBzIdjxXvOjiS+Jeh0S+/2dC
    JUQ7rSYgDyBEtb+lYF4Gko9YVdMNvALebtdUkctL2Dcybh5wGdFS+vzlw4GIRExn
    xC6ynCE3D/pthJmUSS9gaU7/MgwlMcmnbGW8+ycRstixQfsjWfg0xSmhN64COnTv
    hzwReafGlfpzJkuB2lGPicR2RrZRlyk9KR3f3u2RiBYPnsxlnlC/nO93lIm2OX/0
    86PJqV2UnQkOA1mNR/8GyY7VQFy+SuhLcYf2Baz9xuboEK//phaRV2QCn8rLTHD0
    rX590zQV2WUtnkeBqWLeaDWCbt6t1zrQVVvYyGbDJlkV6/gNI5wwGVS/m8CktiLA
    jJFlGyjQOvwTQJOeU0Ck1a1IeSvW4taoh2G82fi2VFyOFH5AUEaQsz82+rcCAwEA
    AQKCAgBF8X/Qv9gXuyD1wkNSIjcB5QYhm2D+DJRzntyx6wneAvkwqFcLHYmAbh+S
    7eET9/8JHTDNLJQGb4yvXy7ZiPpNOGpwkI/GcmO8G46L4HdLgWxLoQy1j+kRSRYa
    4eTeiE8DCcfR2PnFQg70eLS1lS4nSlhWX9W4dB0JwtCs/xBfu/xq9LdTn+YHWxLi
    RaXBEmAv++2j4k/07hgOxvANH7pLjLqiItjhujfnEp3e5eYenUuM6uLkqMRd2dh7
    RXzAVj7jT4gMHOtLiKQ+iMr0azshEPTI+SjTwPTg/xIpLULDdmACx1pQ2paF9YAQ
    Xj/cZlluJQdItG+6NKia4R1dJm3xSfse463k+pkVupWICbxUWjvBFyxEjPILF7Er
    e8fTBRv+0XsoJdhv8EDkT/REZpW0q+kqCP5Xbd+M2Ew1AIYx/w9WxJLA+DH/MMZB
    KT1cN0pTNnh11azvw/EIVU8zcP7JzdROSb8quIRXIA3Vvj7lc9xJXEwmBH25pnCo
    NKEr6WjT8XJX3SOhYo2ECYFIn5Fj7u+PX/pwScMXsVa4lldFGaEkbfTg2kaU2Czx
    U7gaMcZRvs8xh/qkVQWGHj5jVW641yap0OJgaQLu+0N7xNa05CJDllr/JscaWid+
    UviPXdnXLfSNXNOu5ynJoyv076z5EQOO9Ump0Ha4QSZUOaVsUQKCAQEA+QM5knyJ
    PhJYfeC/7BCSa7NvAkWkxBQ0SmdNReFF9sYuf37tps/hc/e6x2M2huk/F5RG2JB0
    5hksKHuvryM1pFhOXl0H9th+c5lRjplYOnARCz6X6OXYpijiinrlIdZmNTGduOjj
    oG4MClQh+4zVb6mUP2TVXeOqwbMGZESEM9mBzAScjDpr0CqC78Kskxm2Q/Mwa+an
    nRRgWgugonU6nMg31BCMlTDqH5zUl46Pj8hCtyl4QxHxn2MsNhhQXzMhAsDTxns3
    SnkrqGjXpO9WBDT6CuFKilvWlvzlMIc7xjSebxpg7AvdHF69GSxsqDcPWUIGkoKU
    dPSb7l4O36M0VQKCAQEA64Hl+GVwf+BFdmhltBMPe2lF8C1IQ4OQbH5NK8sGguKG
    FU8NXQCLTukqVrjvSj2mSmtbpfQ5CCgocKcui2pmyLtf+UfxHw9IL5QGvKyS4AmX
    heEFvLjDNMObYwTIXsZsQFf7YPH23ukRabE7zXODk4PkUTNv9v2ipXj0QDY1tF32
    h6xDRxUn73xjCrW5dPm96tN+nRCA5J02ex26emv1vGbYIt/ldR29KaLVqcFe/H79
    2eEy5MyZZcBHIQMFX31gSRJ0qR5caPYlklylpuCm1CqnISCQEkQG9xN55IjKWyAA
    ghIGnB82nzWcRf9qo2QO3Ta9zJh/RF6nyGp0rdpe2wKCAQB5AkAwF6T6LSAjy9x4
    c3U0MXZ4vC9duhPPNHQwyVCeo6BlBOGods0w9eomiugsl5y5cK0dANZOG12CLtkp
    WwruWpt67+q24m5Q7ujbS1m8zEj8FebsnwWxeZzdfutqji4NG5dyDHrRs6jWPBxn
    igEOynHofK/TeJe6ma05fLJiIAkbhAIvgxRxjLcknI4QziXsz3lwdh5uD0DjgVMG
    n8Fj/0hiHcizl5mu0x/cpsLNNJx3NgfjUA0DT8ZkY1xrZwVbuSkxAx/TaR72MDzb
    QhOi57u7HdCDfC3EIhGei5lYsKlthHwlOX6yErgCS7xh4p/q2FMpT5ulWlmMdNj1
    hPIhAoIBAQDBwScQi3RY4IyFdDJoSl4sbFnr1XVkhjMl72tSIkCDIhaqJVWbND1o
    eJAqtQ+5hqrvAxBtolXhjhhnRkQW0z0o3G+DSVro8Mu0yRYZ1+kmhP2yWYU81M1U
    9bE7b83hm2GoNjpMcgVnM1zuFbBbwTN5A8OtwqHVFKrhdHeO9IqOj9epm2Hmc1Nd
    xno9b3Da+jTzo3jBg7hnXaha9gRbf8K2c+5SEt5W0la0kJE0jjC1j00OGiai8mkp
    u11JnZCoFSBIPfTYxm/Esu4KUkq+1oiqeUTzDjU5sdoBIHbiPGAvRE7mtCnX/B4W
    MicVt6NmNYW9HbJdRwE9oJptWpgQCF6NAoIBAQChmy3uJ/SFg5h9gMBd4HeLiWpf
    iLGrx1M9ftQRBVXxnOPmqlVCIzDTw9q7qThvAYMcEfPBafl4/TVEOOMMeQRCXknT
    1dsEo53jMCbOG2TebLOGgYKMkXezvieK6XjYCJmRBdncj792aAwzipghMeLMrRQR
    IGtAM+OVf/9EAF2mw1Wup+OjPqN8q6EqF1ujAbezFvI7mgE1slZXZLEu31RhrqTS
    LB3jwlBPVHtOUOKuNLG8GDormxwTDUkP83empUlboJCh+dtdPv19rgpEiqr3ja34
    BvpSoMDvkA5aVrwh2HQl8KEun++bn3sKqGO4kbXSmQpVpJm13dA+a0JCFo8/        
    -----END RSA PRIVATE KEY-----
