CF_DEV_ORG: DPSE-ASIA
CF_UAT_ORG: DPSE-ASIA
CF_PROD_ORG: DPSE-ASIA

MY_ENV_VAR: test-my-env-var

GIT_SSH_URI: ssh://git@git.platform.manulife.io:2222/alan_tsui/mongo-atlas-migrate-demo.git
GIT_PRIVATE_KEY: |
