---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: docker.artifactory.platform.manulife.io/java-ci

inputs:
- name: source

outputs:
- name: target

run:
  path: source/concourse/scripts/artifactory-publish-gradle.sh
