---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: docker.artifactory.platform.manulife.io/java-ci

inputs:
- name: source

run:
  path: source/concourse/scripts/test-linux.sh
